### PR TITLE
AT-24

### PR DESCRIPTION
**Pull request by ivan-rh22**
This adds the option for users to choose their user type (student or teacher) at the moment of signing up. It is currently a working implementation.

### CODE REVIEW

**Comment by JuanTime2Late** [comment]
android still overflows by 40 pixels

**Comment by ivan-rh22** [comment]
> android still overflows by 40 pixels

fixed

**Review by JuanTime2Late — APPROVED** [review]
Tested and confirmed merge and delete when u wish.

**Comment by ivan-rh22** [comment]
simplified code. shows default state on screen now as well.

**Review by JuanTime2Late — APPROVED** [review]
confirmed merging now!

**Pull request merged**
